version: '3'
services:
  back:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
       - "3333:3333"
    working_dir: /var/www
    volumes:
        - ./src:/var/www/src
    networks:
      - besafe-network
    depends_on:
      - db

  db:
    image: "postgis/postgis"
    ports: 
      - "5432:5432"
    volumes:
       - ./.docker:/var/lib/postgrespers
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: asd
      POSTGRES_DB: besafe-db
    networks:
      - besafe-network

#Docker Networks
networks:
  besafe-network:
    driver: bridge
